"""Program Trace Prompting (PTP) factory.

Extends SimulateFactory to inject execution traces as in-context
examples. Instead of showing full I/O pairs (which are too long for
tasks with long inputs like MUSR), PTP shows the chain of function
calls with abbreviated inputs and outputs.

Reference: "Watch Your Steps: Observable and Modular Chains of Thought"
(Cohen et al., arXiv:2409.15359)

Usage via config::

    ptools:
      answer_question_workflow:
        method: ptp
        trace_file: traces.txt

Or programmatically::

    interface.implement_via('ptp', trace_file='traces.txt')
"""

import pathlib
from typing import Callable

from secretagent import config, llm_util, record
from secretagent.core import Interface, register_factory
from secretagent.implement_core import SimulateFactory, _load_template


class PTPFactory(SimulateFactory):
    """Simulate with Program Trace Prompting examples.

    Like SimulateFactory, but injects execution traces (from a trace
    file) into the $examples section of the simulate prompt. Traces
    show the chain of function calls with variable names instead of
    full values, making them much more compact than raw I/O examples.

    Builder kwargs:
        trace_file: path to a text file containing formatted PTP traces
            (generated by ``secretagent.learn.traces.extract_ptp_traces``)
    """

    def build_fn(self, interface: Interface,
                 trace_file: str | None = None,
                 **prompt_kw) -> Callable:
        # Load traces at build time
        traces_text = ''
        if trace_file:
            traces_text = pathlib.Path(trace_file).read_text()

        def result_fn(*args, **kw):
            with config.configuration(**prompt_kw):
                # Build prompt with traces injected as examples
                prompt = self.create_prompt(
                    interface, *args, _traces_text=traces_text, **kw)
                llm_output, stats = llm_util.llm(
                    prompt, config.require('llm.model'))
                try:
                    return_type = interface.annotations.get('return', str)
                    answer = self.parse_output(return_type, llm_output)
                except Exception as ex:
                    record.record(func=interface.name, args=args, kw=kw,
                                  output=f'**exception**: {ex}', stats=stats)
                    raise
                record.record(func=interface.name, args=args, kw=kw,
                              output=answer, stats=stats)
                return answer
        return result_fn

    def create_prompt(self, interface, *args, _traces_text='',
                      examples=None, **kw):
        """Build simulate prompt with PTP traces as examples."""
        template = _load_template('simulate.txt')
        input_args = interface.format_args(*args, **kw)
        if not input_args.strip():
            raise ValueError(f'input_args null for {args=} {kw=}')

        if config.get('llm.thinking'):
            thoughts = "<thought>\nANY THOUGHTS\n</thought>\n"
        else:
            thoughts = ""

        # Use traces as examples (instead of doctest I/O pairs)
        examples_text = _traces_text if _traces_text else ''

        prompt = template.substitute(
            dict(stub_src=interface.src,
                 input_args=input_args,
                 thoughts=thoughts,
                 examples=examples_text))
        return prompt


register_factory('ptp', PTPFactory())
