"""Wrap generated code into a callable pipeline.

A Pipeline compiles LLM-generated code into a function whose namespace
contains the available ptool Interface objects, so calling the function
dispatches through the normal Interface.__call__ path (recording,
config, caching all work).
"""

import textwrap
from typing import Any, Callable

from secretagent.core import Interface


class Pipeline:
    """A pipeline generated by the orchestrator.

    Wraps generated Python code into a callable function that has
    access to ptools via its exec namespace.
    """

    def __init__(self, code: str, entry_signature: str,
                 namespace: dict[str, Any]):
        self.code = code
        self.entry_signature = entry_signature
        self._fn = self._compile(code, entry_signature, namespace)

    @staticmethod
    def _compile(code: str, entry_signature: str,
                 namespace: dict[str, Any]) -> Callable:
        """Compile generated code into a callable function.

        Wraps the code body in the entry_signature to create a proper
        function, then exec's it in a namespace containing the ptools.
        """
        # Normalize indentation: LLMs sometimes return code where the
        # first line has no indent but subsequent lines do.  dedent only
        # strips *common* whitespace, so it won't help in that case.
        # Fix by detecting the indent of the second non-blank line and
        # prepending it to the first line so dedent works correctly.
        lines = code.splitlines()
        if len(lines) > 1:
            # Find indent of first non-blank line after the first
            for line in lines[1:]:
                if line.strip():
                    second_indent = len(line) - len(line.lstrip())
                    break
            else:
                second_indent = 0
            first_indent = len(lines[0]) - len(lines[0].lstrip())
            if second_indent > first_indent:
                lines[0] = ' ' * second_indent + lines[0].lstrip()
                code = '\n'.join(lines)
        indented_body = textwrap.indent(textwrap.dedent(code), '    ')
        func_src = f'{entry_signature}\n{indented_body}'

        func_name = entry_signature.split('(')[0].replace('def ', '').strip()

        exec_namespace = dict(namespace)
        exec(func_src, exec_namespace)

        return exec_namespace[func_name]

    def __call__(self, *args, **kwargs):
        return self._fn(*args, **kwargs)

    @property
    def source(self) -> str:
        """Full source code of the generated function."""
        indented_body = textwrap.indent(textwrap.dedent(self.code), '    ')
        return f'{self.entry_signature}\n{indented_body}'


def _entry_signature_from_interface(interface: Interface) -> str:
    """Build a def-line string from an Interface's annotations."""
    annotations = interface.annotations
    param_parts = []
    for name, ann in annotations.items():
        if name == 'return':
            continue
        type_name = getattr(ann, '__name__', str(ann))
        param_parts.append(f'{name}: {type_name}')
    return_type = annotations.get('return', Any)
    return_name = getattr(return_type, '__name__', str(return_type))
    return f'def {interface.name}({", ".join(param_parts)}) -> {return_name}:'


def build_pipeline(
    code: str,
    entry_interface: Interface,
    tool_interfaces: list[Interface],
) -> Pipeline:
    """Build a Pipeline from generated code and available tools.

    Args:
        code: generated function body
        entry_interface: the workflow Interface this pipeline implements
        tool_interfaces: interfaces whose implementations should be available

    Returns:
        A callable Pipeline.
    """
    namespace: dict[str, Any] = {}
    for iface in tool_interfaces:
        # Interface.__call__ dispatches to implementation, so recording etc. works
        namespace[iface.name] = iface

    entry_signature = _entry_signature_from_interface(entry_interface)

    return Pipeline(code, entry_signature, namespace)
