llm:
  model: together_ai/deepseek-ai/DeepSeek-V3.1
cachier:
  cache_dir: /Users/wcohen/Documents/code/secretagent/benchmarks/bbh/sports_understanding/llm_cache
evaluate:
  result_dir: /Users/wcohen/Documents/code/secretagent/benchmarks/bbh/sports_understanding/model_sweep_results
  expt_name: analyze_sentence_gpt-oss-120b
dataset:
  split: valid
  shuffle_seed: 137
ptools:
  analyze_sentence:
    method: simulate
    model: together_ai/openai/gpt-oss-120b
  sport_for:
    method: simulate
    model: together_ai/openai/gpt-oss-20b
  consistent_sports:
    method: simulate
    model: together_ai/openai/gpt-oss-20b
  are_sports_in_sentence_consistent:
    method: direct
    fn: ptools.sports_understanding_workflow
